// import { fileURLToPath } from "url";
// import { dirname } from "path";
// const __filename = fileURLToPath(import.meta.url);
// const __dirname = dirname(__filename);
// export default __dirname;
export const PORT = 8080;
export const PRODUCTS_JSON = "db/products.json";
export const CART_JSON = "db/cart.json";
export const MONGODB_CNX_STR = 'mongodb+srv://koriditmeyer:BPfgRwT28IHTHunI@spaapp.bgppebz.mongodb.net/ecommerce' //MONGO ATLAS
//export const MONGODB_CNX_STR = 'mongodb://127.0.0.1:27017/ecommerce' //local MONGO DB connection

export const SESSION_SECRET = "dfgdfgdfe45#23@@we2_?>sd" //generated by me

export const githubAppId = '720030'
export const githubClienteId = 'Iv1.6b09a305cc1bdb90'
export const githubClientSecret = 'b359e062b9d9fee69997feb954f9082255cbc250'
export const githubCallbackUrl = 'http://localhost:8080/githubcallback'